[versions]
kotlin = "2.2.20"
ktor = "3.3.1"
trainy = "1.12.23-SNAPSHOT"
sqldelight = "2.2.1"

[libraries]
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-serialization-csv = { group = "de.brudaswen.kotlinx.serialization", name = "kotlinx-serialization-csv", version = "2.1.0" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.17" }
stdx-envconf = { group = "dev.schlaubi", name = "stdx-envconf", version = "2.0.0" }

operatorclient = { group = "app.trainy", name = "operator-client", version.ref ="trainy" }

sqldelight-jdbc-driver = { group = "app.cash.sqldelight", name = "jdbc-driver", version.ref = "sqldelight" }
sqldelight-postgresql-dialect = { group = "app.cash.sqldelight", name = "postgresql-dialect", version.ref = "sqldelight" }
postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.7" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "6.3.0" }
logback = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.20" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
